### ISSUE TITLE
Parsing issues & inconsistencies

### ISSUE THREAD

**Issue by Balint837** [MinecraftNight4/bot_muse#1]
### The "@" character isn't parsed properly:
![image](https://user-images.githubusercontent.com/71632376/233397773-52258525-2516-4cf2-868b-e431a4f9be4d.png)
![image](https://user-images.githubusercontent.com/71632376/233397714-c2c1b0b1-a9b6-409a-a59d-addf5e0195fc.png)

### Although it seems like there are other issues present:
![image](https://user-images.githubusercontent.com/71632376/233397905-dd47f73d-b6a2-4a43-b26e-18a2ed1183f0.png)

### "\<none\>" is apparently a song & "\<b\>" displayed in strawberry godzilla's name:
![image](https://user-images.githubusercontent.com/71632376/233396168-13c0529b-2297-4bbb-ae68-fd0a6457f656.png)

### Inconsistent errors:
![image](https://user-images.githubusercontent.com/71632376/233402385-254b6ad3-ac14-4776-a38f-12209100dd4e.png)

### (This could be intentional?) bpm:x+ works, while bpm:x- doesn't:
**(Neither does bpm:x on it's own, even though bpm:x-x works.)**
![image](https://user-images.githubusercontent.com/71632376/233402811-adbf5369-93f2-497e-8236-f8937c1af8af.png)

### 6th language no way?!?!
![image](https://user-images.githubusercontent.com/71632376/233408058-a9e10548-48ab-427e-99e9-816c32357d38.png)

### This speaks for itself:
![image](https://user-images.githubusercontent.com/71632376/233408666-82a53c18-c8ad-4169-b5f0-a29a11cf1c53.png)

### **And that's all he wrote.**

**Comment by MinecraftNight4** [comment]
- Album Index fixed
- Author Index fixed
- "by" filter fixed 
- "des" filter fixed 
- "<b>sᴛʀᴀᴡʙᴇʀʀʏ ɢᴏᴅᴢɪʟʟᴀ</b>" song name fixed
- Language list fixed
- Cooldown Arg. Fixed

**Comment by MinecraftNight4** [comment]
BPM:
![image](https://user-images.githubusercontent.com/42017416/233471195-b284d192-41f6-4098-861d-0527d604382c.png)

Song Filters fixed:
![image](https://user-images.githubusercontent.com/42017416/233472040-57d07db2-00c6-45f8-944b-7c908e2ff58f.png)

Lang:
![image](https://user-images.githubusercontent.com/42017416/233472187-27dfffed-a0a5-4034-b32b-cac703ce364b.png)

Fixed cooldown argument threshold:
![image](https://user-images.githubusercontent.com/42017416/233472457-0bd5a8c3-482b-4835-b378-3538af33cfa3.png)
